version: '3'
services:
    php-apache:
      build: .
      ports:
        - 80:80
      links:
        - db
      volumes:
          - ./:/var/www/html

    db:
      image: mysql
      ports:
       - "3306:3306"
      environment:
        MYSQL_DATABASE: sitedinamico
        MYSQL_ROOT_PASSWORD: alefcristian
        MYSQL_USER: god_dev_alef
        MYSQL_PASSWORD: alefcristian

